server:
    port: 7036
spring:
    redis:
        host: 172.16.5.22
        port: 6379
        timeout: 20000
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
        password:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.1.105:3306/spring?characterEncoding=utf8&useSSL=true
        username: root
        password: Jkdz8888
mybatis:
    mapper-locations: classpath*:com/haxiha/framework/dao/user/*.xml
    type-aliases-package: com/haxiha/framework/domain/**,com/haxiha/framework/intf/**
